### ISSUE TITLE
Dataset Structure is different..

### ISSUE THREAD

**Issue by sung-sidewalk** [wangjiongw/FreeMan_API#4]
Hello, 
I have downloaded dataset via OpenXLab.
However, the data structure was not equal to what you've mentioned in readme file.

Also, when I checked video fps, it was 25.

Can you tell me what i did wrong?

Thank you!

**Comment by sung-sidewalk** [comment]
Also, I couldn't bbox annotation.

**Comment by wangjiongw** [comment]
> Hello, I have downloaded dataset via OpenXLab. However, the data structure was not equal to what you've mentioned in readme file.
> 
> Also, when I checked video fps, it was 25.
> 
> Can you tell me what i did wrong?
> 
> Thank you!

Thanks for your questions.
1. To upload the dataset efficiently, we compress file items into zip files. The file structure is README is the one that the code targets. So you may uncompress the files to the structure or make your own and modify corresponding code accordingly.
2. I'm sorry that the folder is wrongly named. FPS of current videos uploaded is 25 and we will correct this as soon as possible.
3. bbox annotation was accidently missed in uploading. Thanks for your reminder and we will upload this after final check.

**Comment by sung-sidewalk** [comment]
Thank you very much for the update! 👍

**Comment by sung-sidewalk** [comment]
And also it would be lovely noticing when upload is complete!
