### ISSUE TITLE
Release of action labels

### ISSUE THREAD

**Issue by FreemanG** [wangjiongw/FreeMan_API#6]
Thanks for releasing such a big dataset.

In your paper, you mentioned 123 #Action in this dataset. Will you release the action labels?

**Comment by wangjiongw** [comment]
Sorry for late reply. The action annotation file has been released on [this link](https://huggingface.co/datasets/wjwow/FreeMan/blob/main/FreeMan_actions.csv). Please check it out.

Currently, we only release short action category labels, and we are planing to give some dense caption in recent future.

**Comment by FreemanG** [comment]
Thanks for your kind sharing.
